### ISSUE TITLE
Add method to see if a String is made up exclusively by one or more emojis

### ISSUE THREAD

**Issue by Jasperav** [sigpwned/emoji4j#70] opened 2023-06-19 16:11 UTC
I want to find out if a String holds exclusively emojis and, if possible, how many emojis there are in a String. I now have this code, but it fails because it also says is an emoji when the input is an emoji and some text:

```
fun String.isEmoji(): Boolean {
    val matcher = GraphemeMatcher(this)

    return if (matcher.find()) {
        return !matcher.find()
    } else {
        false
    }
}
```

I want to make sure it works with skintones, family emojis, etc. I tried checking other properties with reflection, like the `length` or `index`, but they all broke things in the end.

**Comment by Jasperav** [comment] 2023-06-19 16:25
I tried the `matches` method and for some skintones emojis it works, however, it fails on this emoji: 👩🏾‍

**Comment by Jasperav** [comment] 2023-06-19 17:45
Maybe a `matches_all` or something? In which `matches` just matches a single emoji and `matches_all` 1 or more?

**Comment by Jasperav** [comment] 2023-06-27 08:37
@sigpwned is this library still maintained?

**Comment by sigpwned** [comment] 2023-06-28 13:37
It is! Let me have a look here today.

**Comment by sigpwned** [comment] 2023-06-28 16:38
OK, I've had a look, and I'm having trouble reproducing this bug.

Specifically, I've added tests for [skin tones](https://github.com/sigpwned/emoji4j/blob/main/emoji4j-core/src/test/java/com/sigpwned/emoji4j/core/GraphemeMatcherTest.java#L100) and [multiple emoji](https://github.com/sigpwned/emoji4j/blob/main/emoji4j-core/src/test/java/com/sigpwned/emoji4j/core/GraphemeMatcherTest.java#L115), and they seem to pass.

I did make some tweaks to the matching algorithm. Maybe try upgrading to the new version?

Regarding determining if a string is made entirely of emoji, check out `https://github.com/sigpwned/emoji4j/wiki/Cookbook#is-string-all-emojis`. Is this kind of what you had in mind?

**Comment by Jasperav** [comment] 2023-06-29 05:51
@sigpwned Thanks a lot for taking your time and looking into the issues I reported! I can tell that with the new versions you published along with the examples in the Cookbook, all tests just passed, which is awesome! 

I just have a small question about the method `isStringAllEmoji`, it works accordingly, but don't you want this method to be in the library itself? Now everyone needs to copy paste it, while it works as a charm :).

Thanks again!

**Comment by sigpwned** [comment] 2023-06-29 20:40
Glad it's what you were looking for!

> I just have a small question about the method isStringAllEmoji, it works accordingly, but don't you want this method to be in the library itself? Now everyone needs to copy paste it, while it works as a charm :)

That's a fair question!

Philosophically, I believe that libraries should provide tools as opposed to solutions, as a rule. If a library doesn't provide the "parts" that users need "put together" the solutions they need quickly and easily, then that's the library's fault. But if the library doesn't have a method for Every Possible Use Case, then that's OK because the solution is up to the user.

Of course, there's a trade-off here, though. It makes absolute sense to put the most common methods for the most common use cases into the library. (The absence of a `Stream` was an obvious defect, for example!) But I don't want to ship every solution that anybody needs to everybody either, since that's just wasted space in the JAR.

At the end of the day, it's purely a matter of taste and judgment. But if I got a lot of feedback that `isStringAllEmoji` is actually a core use case, then I'd happily move it into the library!

Please let me know if there's anything else you need from the library!

**Comment by sigpwned** [comment] 2023-06-29 20:40
Closing now -- feel free to re-open if needed!

**Closed by sigpwned** 2023-06-29 20:40 UTC
